---
abstract: 'Module contaning danish zipcodes for validation and deployment'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Data::Dumper: '0'
  Data::FormValidator: '0'
  English: '0'
  Env: '0'
  File::Spec: '0'
  Test::CPAN::Changes: '0'
  Test::Class: '0'
  Test::Exception: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Prereq::Build: '0'
  Test::Taint: '0'
configure_requires:
  Module::Build: '0.40'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-GL-Postalcode
provides:
  Business::GL::Postalcode:
    file: lib/Business/GL/Postalcode.pm
    version: '0.01'
  Class::Business::GL::Postalcode:
    file: lib/Class/Business/GL/Postalcode.pm
    version: '0.01'
requires:
  Carp: '0'
  Data::Handle: '0'
  Exporter: '0'
  List::Util: '0'
  Params::Validate: '0'
  Scalar::Util: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-GL-Postalcode
  homepage: https://github.com/jonasbn/perl-Business-GL-Postalcode
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: https://github.com/jonasbn/perl-Business-GL-Postalcode
version: '0.01'
